code/view/HabitScreen.fxml

I finished the habit main screen as far as wireframe is concerned and I put the project directory together. More skeletons will come from this branch.

UI skeleton

---

code/src/main/java/habit_mode/Main.java
code/src/main/java/habit_mode/model/Frequency.java
code/src/main/java/habit_mode/model/Habit.java
code/src/main/java/habit_mode/model/ServerCommunicator.java
code/src/main/java/habit_mode/model/local_implementation/LocalServerCommunicator.java
code/src/main/java/habit_mode/view_model/HabitViewModel.java
code/src/test/java/habit_mode/test/model/habit/TestConstructor.java
code/src/test/java/habit_mode/test/model/habit/TestSetters.java
code/src/test/java/habit_mode/test/view_model/TestAddHabit.java
code/src/test/java/habit_mode/test/view_model/TestSetHabitCompletion.java

Feature missing documentation

---

code/src/main/java/habit_mode/view/codebehind/HabitScreenCodeBehind.java
code/src/main/java/habit_mode/view/codebehind/LoginScreen.java
code/src/main/resources/habit_mode/view/codebehind/HabitScreen.fxml
code/src/main/resources/habit_mode/view/codebehind/LoginScreen.fxml

Majority of development planned for this week is completed as well as a few major features.

Login&habitscreen functions

---

.gitignore
server/habit_mode_server.py
server/server.py
server/service_manager.py
server/sudoku_puzzle.py
server/user_data.py

Created the server and add the ability for users to register an account. Checks and requirements are currently placeholders until they are hammered out.

Add user registration to server

---

code/src/main/java/habit_mode/view/codebehind/LoginScreen.java
code/src/main/resources/habit_mode/view/codebehind/LoginScreen.fxml

Implemented a register button instead of changing the login button's features to help increase readability and not violate SRP.
Added the register button and its event handler in the login screen code behind. For now, the register button calls the login button's event handler when clicked until implementation is done.

Update registration ui

---

server/authentication_manager.py
server/habit_mode_server.py
server/server.py
server/service_manager.py
server/tests/_request_handler/_get_missing_fields_test.py
server/tests/_request_handler/_login_test.py
server/tests/_request_handler/_register_user_test.py
server/tests/_request_handler/constructor_test.py
server/tests/_request_handler/handle_request_test.py
server/tests/authentication_manager/constructor_test.py
server/tests/authentication_manager/generate_and_store_key_for_username_test.py
server/tests/authentication_manager/get_token_for_username_test.py
server/tests/authentication_manager/get_username_for_token_test.py
server/tests/service_manager/create_user_test.py
server/tests/service_manager/get_data_for_user_test.py
server/tests/user_data/user_data_constructor_test.py
server/user_data.py

Adds logging into the server, allowing the user to retrieve a unique access token that will be used to interact with the account in the future.

Feature server login

---

code/src/main/java/habit_mode/model/ServerCommunicator.java
code/src/main/java/habit_mode/model/local_implementation/LocalServerCommunicator.java
code/src/main/java/habit_mode/view/codebehind/LoginScreen.java
code/src/main/java/habit_mode/view_model/HabitViewModel.java
code/src/main/java/habit_mode/view_model/LoginScreenViewModel.java
code/src/test/java/habit_mode/test/model/local_implementation/LocalServerCommunicator/TestAddHabit.java
code/src/test/java/habit_mode/test/model/local_implementation/LocalServerCommunicator/TestCompleteHabit.java
code/src/test/java/habit_mode/test/model/local_implementation/LocalServerCommunicator/TestRemoveHabit.java
code/src/test/java/habit_mode/test/model/local_implementation/LocalServerCommunicator/TestUpdateSudokuPuzzle.java
code/src/test/java/habit_mode/test/model/local_implementation/LocalServerCommunicator/TestValidateLogin.java
code/src/test/java/habit_mode/test/view_model/LoginScreenViewModel/TestVerifyLogin.java

Beforehand we had used booleans to trade feedback for functions related to managing habits and login credentials. Now that we're actually using success codes all the tests and most of the methods in the ServerCommunicator abstract class had to be updated so that the server can be integrated properly.

Adjusted ServerCommunicator to use SuccessCodes

---

server/backend/server.py
server/habit_mode_server.py
server/tests/_request_handler/constructor_test.py
server/tests/server_tests/run_test.py

Touches up the close server functionality and adds command line arguments for setting the server's socket.
Adds tests for the run method as the server can now be easily closed with a request.

Feature close server

---

code/src/main/java/habit_mode/view/codebehind/LoginScreen.java
code/src/main/java/habit_mode/view_model/LoginScreenViewModel.java
code/src/test/java/habit_mode/test/view_model/LoginScreenViewModel/TestRegisterUser.java

-Implemented the registration event handler in the LoginScreen and linked the process to the LoginScreenViewModel.
-Implemented the emailProperty and registerUser method in the LoginScreenViewModel.
-Created a test file for the LoginScreenViewModel's registerUser method.

Implemented user registration

---

code/src/main/java/habit_mode/model/ServerServerCommunicator.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestCompleteHabits.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestRemoveHabit.java

Implemented the last two methods to be implemented from last sprint. This necessitated the creation of two new string constants. I also implemented the functionality for tracking coins through the server.

Updated ServerServerCommunicator

---

code/src/main/java/habit_mode/view/codebehind/HabitScreenCodeBehind.java
code/src/main/java/habit_mode/view_model/HabitViewModel.java

added a method for determining the remove frequency

Determine Remove Frequency

---

code/src/main/java/habit_mode/model/sudoku/SudokuPuzzle.java
code/src/test/java/habit_mode/test/model/sudoku/sudokuPuzzle/TestIsComplete.java

Implemented the isComplete() method to check if a puzzle is complete or not.

Sudoku Validation

---

code/src/main/java/habit_mode/view/codebehind/HabitScreenCodeBehind.java

Coins now do not update until habit is pushed to completed list view

Fixed adding coins

---

server/backend/server.py
server/backend/sudoku_generator.py
server/backend/sudoku_puzzle.py
server/backend/user_data.py
server/tests/_request_handler/_retrieve_data_test.py
server/tests/sudoku_generator/generate_sudoku_puzzle_test.py
server/tests/sudoku_puzzle/constructor_test.py
server/tests/sudoku_puzzle/get_set_number_at_test.py
server/tests/sudoku_puzzle/get_set_number_locked_at_test.py
server/tests/sudoku_puzzle/get_set_solution_at_test.py
server/tests/sudoku_puzzle/is_complete_test.py
server/tests/sudoku_puzzle/is_number_valid_at_test.py
server/tests/sudoku_puzzle/is_solution_valid_at_test.py
server/tests/sudoku_puzzle/is_solution_valid_test.py
server/tests/sudoku_puzzle/properties_test.py

Add sudoku puzzle generation to the server and updates the `retrieve_data` request to send the currently filled in numbers and which numbers are locked.
Currently, sudoku puzzles are only generated with 180 degree rotational symmetry.

Feature server sudoku puzzle

---

server/backend/server.py
server/backend/user_data.py

Update type hints to use types from the "typing" module, rather than Python's built in types (ie: "list[int]" vs "List[int]")

Correct wrong type hints

---

code/src/main/java/habit_mode/model/ServerServerCommunicator.java
code/src/main/java/habit_mode/view_model/HabitViewModel.java
code/src/main/java/habit_mode/view_model/LoginScreenViewModel.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestCompleteHabits.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestGetHabits.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestRegisterCredentials.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestRemoveHabit.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestValidateLogin.java

This feature focuses on fixing the issue of requiring the server to be run to actually perform the tests on the serverservercommunicator.

Serverservercommunicator testing

---

server/backend/server.py
server/tests/server_tests/run_test.py

Add a test to make sure that the server creates the appropriate response when the RequestHandler raises an uncaught exception.

Add server test for RequestHandler exceptions

---

server/backend/user_data.py

Re-added missing post conditions that were removed after a bad merge.

Fix missing post conditions

---

code/src/main/java/habit_mode/view_model/HabitViewModel.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestAddHabit.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestGetters.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestRemoveHabit.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestSendCompletedHabit.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestSetHabitCompletion.java
code/src/test/java/habit_mode/test/view_model/HabitViewModel/TestUpdateHabit.java

Resolving the constructor chaining issue in the view model.
Refactored the constructor chaining to be simpler and more extendable.
Ensured all tests and mvn verify validate after this test.

Refactoring habit view model

---

code/src/main/java/habit_mode/model/ServerCommunicator.java
code/src/main/java/habit_mode/model/ServerServerCommunicator.java
code/src/main/java/habit_mode/model/local_implementation/LocalServerCommunicator.java
code/src/test/java/habit_mode/test/model/serverservercommunicator/TestBuyHint.java

The client is now prepared to communicate with the server for buying hints.

Serverservercommunicator buy hints
